apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-payments-local-config
  namespace: fcg-payments
  labels:
    app.kubernetes.io/name: fcg-payments
    environment: local
data:
  ASPNETCORE_ENVIRONMENT: "Docker"
  ASPNETCORE_URLS: "http://+:8080"
  MongoDbSettings__ConnectionString: "mongodb://mongodb-service.fcg-infra.svc.cluster.local:27017"
  MongoDbSettings__DatabaseName: "Payments"
  KafkaSettings__BootstrapServers: "kafka-service.fcg-infra.svc.cluster.local:29092"
  KafkaSettings__GroupId: "fcg-payments-consumer-group"
  KafkaSettings__UseSaslSsl: "false"
  KafkaSettings__Topics__UserCreated: "user-created"
  KafkaSettings__Topics__OrderPlaced: "order-placed"
  KafkaSettings__Topics__PaymentProcessed: "payment-processed"
  Serilog__WriteTo__1__Args__serverUrl: "http://seq-service.fcg-infra.svc.cluster.local:5341"
  JwtSettings__Issuer: "FCG-User"
  JwtSettings__Audience: "FCG-Client"
  JwtSettings__AccessTokenExpirationMinutes: "60"
  JwtSettings__RefreshTokenExpirationDays: "7"
