apiVersion: v1
kind: ConfigMap
metadata:
  name: fcg-payments-config
  namespace: fcg-payments
  labels:
    app.kubernetes.io/name: fcg-payments
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  MongoDbSettings__DatabaseName: "Payments"
  KafkaSettings__BootstrapServers: "fcg-kafka.servicebus.windows.net:9093"
  KafkaSettings__SaslUsername: "$ConnectionString"
  KafkaSettings__GroupId: "fcg-payments-consumer-group"
  KafkaSettings__UseSaslSsl: "true"
  KafkaSettings__Topics__UserCreated: "user-created"
  KafkaSettings__Topics__OrderPlaced: "order-placed"
  KafkaSettings__Topics__PaymentProcessed: "payment-processed"
  Observability__ServiceName: "FCG.Payments"
  Observability__EnableOtlpExporter: "false"
  Observability__OtlpEndpoint: ""
  JwtSettings__Issuer: "FCG-User"
  JwtSettings__Audience: "FCG-Client"
  JwtSettings__AccessTokenExpirationMinutes: "60"
  JwtSettings__RefreshTokenExpirationDays: "7"
