<Project Sdk="Microsoft.NET.Sdk">

<ItemGroup>
		<PackageReference Include="Confluent.Kafka" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FCG.Payments.Application\FCG.Payments.Application.csproj" />
		<ProjectReference Include="..\FCG.Payments.Domain\FCG.Payments.Domain.csproj" />
	</ItemGroup>

</Project>
