{
 "title": "FCG Payments - Payments Overview",
 "tags": [
  "fcg-payments",
  "payments"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Approved Payments (30m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payments_processed_total{status=\"approved\"}[30m]))"
    }
   ]
  },
  {
   "title": "Rejected Payments (30m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(payments_processed_total{status=\"rejected\"}[30m]))"
    }
   ]
  },
  {
   "title": "P95 Process Payment Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(application_command_duration_ms_bucket{command=\"ProcessPaymentRequest\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Processed Payments by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(payments_processed_total[5m])) by (status, reason)",
     "legendFormat": "{{status}} {{reason}}"
    }
   ]
  },
  {
   "title": "Processed Amount per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(rate(payment_amount_sum[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Payment Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{service_name=\"FCG.Payments\"} |= \"Payment\""
    }
   ]
  }
 ]
}